/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './base-locale.component.scss.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '@angular/router';
import * as i3 from './base-locale.component';
import * as i4 from '@ngrx/store';
import * as i5 from '../../globals/globals';
const styles_BaseLocaleComponent:any[] = [i0.styles];
export const RenderType_BaseLocaleComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_BaseLocaleComponent,data:{}});
export function View_BaseLocaleComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,16777216,(null as any),(null as any),1,'router-outlet',
      ([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
      i1.ɵdid(1,212992,(null as any),0,i2.RouterOutlet,[i2.ChildrenOutletContexts,
          i1.ViewContainerRef,i1.ComponentFactoryResolver,[8,(null as any)],i1.ChangeDetectorRef],
          (null as any),(null as any)),(_l()(),i1.ɵted(-1,(null as any),['\n']))],
      (_ck,_v) => {
        _ck(_v,1,0);
      },(null as any));
}
export function View_BaseLocaleComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-base-locale',
      ([] as any[]),(null as any),(null as any),(null as any),View_BaseLocaleComponent_0,
      RenderType_BaseLocaleComponent)),i1.ɵdid(1,114688,(null as any),0,i3.BaseLocaleComponent,
      [i4.Store,i2.Router,i5.Globals],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const BaseLocaleComponentNgFactory:i1.ComponentFactory<i3.BaseLocaleComponent> = i1.ɵccf('app-base-locale',
    i3.BaseLocaleComponent,View_BaseLocaleComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvdm92YS9Qcm9qZWN0cy9zZWNyZXRzL2NsaWVudC9zcmMvYXBwL2Jhc2UtbG9jYWxlL2Jhc2UtbG9jYWxlLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL3ZvdmEvUHJvamVjdHMvc2VjcmV0cy9jbGllbnQvc3JjL2FwcC9iYXNlLWxvY2FsZS9iYXNlLWxvY2FsZS5jb21wb25lbnQudHMiLCJuZzovLy9ob21lL3ZvdmEvUHJvamVjdHMvc2VjcmV0cy9jbGllbnQvc3JjL2FwcC9iYXNlLWxvY2FsZS9iYXNlLWxvY2FsZS5jb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvdm92YS9Qcm9qZWN0cy9zZWNyZXRzL2NsaWVudC9zcmMvYXBwL2Jhc2UtbG9jYWxlL2Jhc2UtbG9jYWxlLmNvbXBvbmVudC50cy5CYXNlTG9jYWxlQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPHJvdXRlci1vdXRsZXQ+PC9yb3V0ZXItb3V0bGV0PlxuIiwiPGFwcC1iYXNlLWxvY2FsZT48L2FwcC1iYXNlLWxvY2FsZT4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTthQUFBOzBEQUFBO1VBQUEsNkJBQStCOztRQUEvQjs7OztvQkNBQTtNQUFBO29DQUFBLFVBQUE7TUFBQTtJQUFBOzs7OyJ9
