/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './showroom-form.component.scss.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './showroom-form.component';
import * as i3 from '@ngrx/store';
import * as i4 from '../../data-services/admin-interaction-data';
const styles_ShowroomFormComponent:any[] = [i0.styles];
export const RenderType_ShowroomFormComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_ShowroomFormComponent,data:{}});
export function View_ShowroomFormComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted(-1,(null as any),['\n  showroom-form works!\n'])),(_l()(),i1.ɵted(-1,
      (null as any),['\n']))],(null as any),(null as any));
}
export function View_ShowroomFormComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-showroom-form',
      ([] as any[]),(null as any),(null as any),(null as any),View_ShowroomFormComponent_0,
      RenderType_ShowroomFormComponent)),i1.ɵdid(1,245760,(null as any),0,i2.ShowroomFormComponent,
      [i3.Store,i4.AdminInteractionData],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const ShowroomFormComponentNgFactory:i1.ComponentFactory<i2.ShowroomFormComponent> = i1.ɵccf('app-showroom-form',
    i2.ShowroomFormComponent,View_ShowroomFormComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvdm92YS9Qcm9qZWN0cy9zZWNyZXRzL2NsaWVudC9zcmMvYXBwL2FkbWluL2FkbWluLWNvbnRlbnQvc2hvd3Jvb20tZm9ybS9zaG93cm9vbS1mb3JtLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL3ZvdmEvUHJvamVjdHMvc2VjcmV0cy9jbGllbnQvc3JjL2FwcC9hZG1pbi9hZG1pbi1jb250ZW50L3Nob3dyb29tLWZvcm0vc2hvd3Jvb20tZm9ybS5jb21wb25lbnQudHMiLCJuZzovLy9ob21lL3ZvdmEvUHJvamVjdHMvc2VjcmV0cy9jbGllbnQvc3JjL2FwcC9hZG1pbi9hZG1pbi1jb250ZW50L3Nob3dyb29tLWZvcm0vc2hvd3Jvb20tZm9ybS5jb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvdm92YS9Qcm9qZWN0cy9zZWNyZXRzL2NsaWVudC9zcmMvYXBwL2FkbWluL2FkbWluLWNvbnRlbnQvc2hvd3Jvb20tZm9ybS9zaG93cm9vbS1mb3JtLmNvbXBvbmVudC50cy5TaG93cm9vbUZvcm1Db21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8cD5cbiAgc2hvd3Jvb20tZm9ybSB3b3JrcyFcbjwvcD5cbiIsIjxhcHAtc2hvd3Jvb20tZm9ybT48L2FwcC1zaG93cm9vbS1mb3JtPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUEsd0VBQUc7YUFBQSxtREFFQztNQUFBOzs7b0JDRko7TUFBQTtzQ0FBQSxVQUFBO01BQUE7SUFBQTs7OzsifQ==
