/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './cabinet.component.scss.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './cabinet.component';
const styles_CabinetComponent:any[] = [i0.styles];
export const RenderType_CabinetComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_CabinetComponent,data:{}});
export function View_CabinetComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'p',[['style',
      'margin-top: 200px;']],(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i1.ɵted(-1,(null as any),['\n  cabinet works!\n'])),
      (_l()(),i1.ɵted(-1,(null as any),['\n']))],(null as any),(null as any));
}
export function View_CabinetComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-cabinet',
      ([] as any[]),(null as any),(null as any),(null as any),View_CabinetComponent_0,
      RenderType_CabinetComponent)),i1.ɵdid(1,114688,(null as any),0,i2.CabinetComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const CabinetComponentNgFactory:i1.ComponentFactory<i2.CabinetComponent> = i1.ɵccf('app-cabinet',
    i2.CabinetComponent,View_CabinetComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvdm92YS9Qcm9qZWN0cy9zZWNyZXRzL2NsaWVudC9zcmMvYXBwL2JyYW5kL2NhYmluZXQvY2FiaW5ldC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS92b3ZhL1Byb2plY3RzL3NlY3JldHMvY2xpZW50L3NyYy9hcHAvYnJhbmQvY2FiaW5ldC9jYWJpbmV0LmNvbXBvbmVudC50cyIsIm5nOi8vL2hvbWUvdm92YS9Qcm9qZWN0cy9zZWNyZXRzL2NsaWVudC9zcmMvYXBwL2JyYW5kL2NhYmluZXQvY2FiaW5ldC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvdm92YS9Qcm9qZWN0cy9zZWNyZXRzL2NsaWVudC9zcmMvYXBwL2JyYW5kL2NhYmluZXQvY2FiaW5ldC5jb21wb25lbnQudHMuQ2FiaW5ldENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxwIHN0eWxlPVwibWFyZ2luLXRvcDogMjAwcHg7XCI+XG4gIGNhYmluZXQgd29ya3MhXG48L3A+XG4iLCI8YXBwLWNhYmluZXQ+PC9hcHAtY2FiaW5ldD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTtNQUFBLGdCQUE4QjtNQUUxQjs7O29CQ0ZKO01BQUE7aUNBQUEsVUFBQTtNQUFBO0lBQUE7Ozs7In0=
