/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './app-routing.module';
import * as i2 from './home/home.component.ngfactory';
import * as i3 from './brand/showroom/showroom.component.ngfactory';
import * as i4 from './brand/cabinet/cabinet.component.ngfactory';
import * as i5 from './brand/events/events.component.ngfactory';
import * as i6 from './admin/admin.component.ngfactory';
import * as i7 from './admin/admin-content/cabinet-form/cabinet-form.component.ngfactory';
import * as i8 from './admin/admin-content/showroom-form/showroom-form.component.ngfactory';
import * as i9 from './admin/admin-content/events-form/events-form.component.ngfactory';
import * as i10 from './page-not-found/page-not-found.component.ngfactory';
import * as i11 from '@angular/router';
import * as i12 from '@angular/common';
import * as i13 from './home/home.component';
import * as i14 from './brand/showroom/showroom.component';
import * as i15 from './brand/cabinet/cabinet.component';
import * as i16 from './brand/events/events.component';
import * as i17 from 'ngx-auth/src/protected.guard';
import * as i18 from './admin/admin.component';
import * as i19 from './admin/admin-content/cabinet-form/cabinet-form.component';
import * as i20 from './admin/admin-content/showroom-form/showroom-form.component';
import * as i21 from './admin/admin-content/events-form/events-form.component';
import * as i22 from './page-not-found/page-not-found.component';
export const AppRoutingModuleNgFactory:i0.NgModuleFactory<i1.AppRoutingModule> = i0.ɵcmf(i1.AppRoutingModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.HomeComponentNgFactory,i3.ShowroomComponentNgFactory,i4.CabinetComponentNgFactory,
              i5.EventsComponentNgFactory,i6.AdminComponentNgFactory,i7.CabinetFormComponentNgFactory,
              i8.ShowroomFormComponentNgFactory,i9.EventsFormComponentNgFactory,i10.PageNotFoundComponentNgFactory]],
              [3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(5120,i11.ActivatedRoute,
          i11.ɵf,[i11.Router]),i0.ɵmpd(4608,i11.NoPreloading,i11.NoPreloading,([] as any[])),
          i0.ɵmpd(6144,i11.PreloadingStrategy,(null as any),[i11.NoPreloading]),i0.ɵmpd(135680,
              i11.RouterPreloader,i11.RouterPreloader,[i11.Router,i0.NgModuleFactoryLoader,
                  i0.Compiler,i0.Injector,i11.PreloadingStrategy]),i0.ɵmpd(4608,i11.PreloadAllModules,
              i11.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i0.NgProbeToken,() => {
            return [i11.ɵb()];
          },([] as any[])),i0.ɵmpd(4608,i11.ɵg,i11.ɵg,[i0.Injector]),i0.ɵmpd(5120,
              i0.APP_INITIALIZER,(p0_0:any) => {
                return [i11.ɵh(p0_0)];
              },[i11.ɵg]),i0.ɵmpd(5120,i11.ROUTER_INITIALIZER,i11.ɵi,[i11.ɵg]),i0.ɵmpd(5120,
              i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
                return [p0_0];
              },[i11.ROUTER_INITIALIZER]),i0.ɵmpd(1024,i11.ɵa,i11.ɵd,[[3,i11.Router]]),
          i0.ɵmpd(512,i11.UrlSerializer,i11.DefaultUrlSerializer,([] as any[])),i0.ɵmpd(512,
              i11.ChildrenOutletContexts,i11.ChildrenOutletContexts,([] as any[])),
          i0.ɵmpd(256,i11.ROUTER_CONFIGURATION,{},([] as any[])),i0.ɵmpd(1024,i12.LocationStrategy,
              i11.ɵc,[i12.PlatformLocation,[2,i12.APP_BASE_HREF],i11.ROUTER_CONFIGURATION]),
          i0.ɵmpd(512,i12.Location,i12.Location,[i12.LocationStrategy]),i0.ɵmpd(512,
              i0.NgModuleFactoryLoader,i0.SystemJsNgModuleLoader,[i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),
          i0.ɵmpd(1024,i11.ROUTES,() => {
            return [[{path:'',pathMatch:'full',component:i13.HomeComponent},{path:'showroom/:name',
                component:i14.ShowroomComponent},{path:'brand/:name',component:i15.CabinetComponent},
                {path:'events/:name',component:i16.EventsComponent},{path:'admin',
                    canActivateChild:[i17.ProtectedGuard],component:i18.AdminComponent,
                    children:[{path:'cabinet',component:i19.CabinetFormComponent},
                        {path:'showroom',component:i20.ShowroomFormComponent},{path:'events',
                            component:i21.EventsFormComponent}]},{path:'not-found',
                    component:i22.PageNotFoundComponent,data:{message:'Page not found'}},
                {path:'**',redirectTo:'not-found'}]];
          },([] as any[])),i0.ɵmpd(1024,i11.Router,i11.ɵe,[i0.ApplicationRef,i11.UrlSerializer,
              i11.ChildrenOutletContexts,i12.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i11.ROUTES,i11.ROUTER_CONFIGURATION,[2,i11.UrlHandlingStrategy],
              [2,i11.RouteReuseStrategy]]),i0.ɵmpd(512,i11.RouterModule,i11.RouterModule,
              [[2,i11.ɵa],[2,i11.Router]]),i0.ɵmpd(512,i1.AppRoutingModule,i1.AppRoutingModule,
              ([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovUHJvZ3JhbW1pbmcvc2VjcmV0cy9jbGllbnQvc3JjL2FwcC9hcHAtcm91dGluZy5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRjovUHJvZ3JhbW1pbmcvc2VjcmV0cy9jbGllbnQvc3JjL2FwcC9hcHAtcm91dGluZy5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
