/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './app.module';
import * as i2 from './app.component';
import * as i3 from './home/home.component.ngfactory';
import * as i4 from './brand/showroom/showroom.component.ngfactory';
import * as i5 from './brand/cabinet/cabinet.component.ngfactory';
import * as i6 from './brand/events/events.component.ngfactory';
import * as i7 from './admin/admin.component.ngfactory';
import * as i8 from './admin/admin-content/cabinet-form/cabinet-form.component.ngfactory';
import * as i9 from './admin/admin-content/showroom-form/showroom-form.component.ngfactory';
import * as i10 from './admin/admin-content/events-form/events-form.component.ngfactory';
import * as i11 from './page-not-found/page-not-found.component.ngfactory';
import * as i12 from '../node_modules/@angular/material/dialog/typings/index.ngfactory';
import * as i13 from '../node_modules/@angular/material/snack-bar/typings/index.ngfactory';
import * as i14 from './base-locale/base-locale.component.ngfactory';
import * as i15 from './app.component.ngfactory';
import * as i16 from '@angular/common';
import * as i17 from '@angular/platform-browser';
import * as i18 from '@angular/animations/browser';
import * as i19 from '@angular/platform-browser/animations';
import * as i20 from '@angular/http';
import * as i21 from '@angular/common/http';
import * as i22 from 'ng-http-loader/pending-interceptor.service';
import * as i23 from 'ngx-auth/src/auth.interceptor';
import * as i24 from './authentication/refresh-authInterceptor';
import * as i25 from './authentication/token-storage.service';
import * as i26 from './authentication/authentication.service';
import * as i27 from 'ngx-auth/src/tokens';
import * as i28 from './authentication/authentication.module';
import * as i29 from 'ngx-auth/src/public.guard';
import * as i30 from '@angular/router';
import * as i31 from 'ngx-auth/src/protected.guard';
import * as i32 from '@angular/animations';
import * as i33 from '@angular/flex-layout';
import * as i34 from '@angular/forms';
import * as i35 from '@angular/cdk/bidi';
import * as i36 from '@angular/cdk/platform';
import * as i37 from '@angular/cdk/observers';
import * as i38 from '@angular/cdk/scrolling';
import * as i39 from '@angular/cdk/a11y';
import * as i40 from '@angular/material/core';
import * as i41 from '@angular/cdk/collections';
import * as i42 from '@angular/cdk/overlay';
import * as i43 from '@angular/material/dialog';
import * as i44 from '@angular/material/snack-bar';
import * as i45 from '@angular/material/select';
import * as i46 from '@angular/material/autocomplete';
import * as i47 from '@ngx-translate/core/src/translate.loader';
import * as i48 from './translate-loader';
import * as i49 from '@ngx-translate/core/src/translate.compiler';
import * as i50 from '@ngx-translate/core/src/translate.parser';
import * as i51 from '@ngx-translate/core/src/missing-translation-handler';
import * as i52 from '@ngx-translate/core/src/translate.store';
import * as i53 from '@ngx-translate/core/src/translate.service';
import * as i54 from 'angular2-image-upload/lib/image-upload/image.service';
import * as i55 from '@ngrx/store';
import * as i56 from './errors/error.service';
import * as i57 from './admin/data-services/admin-http-requests';
import * as i58 from './nav-service/nav-service';
import * as i59 from 'ng-http-loader/spinner/spinner.component';
import * as i60 from '../globals/globals';
import * as i61 from 'ngx-auth/src/auth.module';
import * as i62 from 'ng-http-loader/ng-http-loader.module';
import * as i63 from '@ngx-translate/core/index';
import * as i64 from 'angular2-image-upload/lib/image-upload.module';
import * as i65 from './home/home.component';
import * as i66 from './brand/showroom/showroom.component';
import * as i67 from './brand/cabinet/cabinet.component';
import * as i68 from './brand/events/events.component';
import * as i69 from './admin/admin.component';
import * as i70 from './admin/admin-content/cabinet-form/cabinet-form.component';
import * as i71 from './admin/admin-content/showroom-form/showroom-form.component';
import * as i72 from './admin/admin-content/events-form/events-form.component';
import * as i73 from './page-not-found/page-not-found.component';
import * as i74 from './app-routing.module';
import * as i75 from './reducers/language/lang.reducer';
import * as i76 from './reducers/menu/menu.reducer';
import * as i77 from './reducers/reset-router/reset.reducer';
import * as i78 from '@angular/cdk/portal';
import * as i79 from '@angular/material/tabs';
import * as i80 from '@angular/material/button';
import * as i81 from '@angular/material/form-field';
import * as i82 from '@angular/material/input';
import * as i83 from '@angular/material/radio';
import * as i84 from '@angular/material/card';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.HomeComponentNgFactory,i4.ShowroomComponentNgFactory,i5.CabinetComponentNgFactory,
              i6.EventsComponentNgFactory,i7.AdminComponentNgFactory,i8.CabinetFormComponentNgFactory,
              i9.ShowroomFormComponentNgFactory,i10.EventsFormComponentNgFactory,i11.PageNotFoundComponentNgFactory,
              i12.MatDialogContainerNgFactory,i13.MatSnackBarContainerNgFactory,i13.SimpleSnackBarNgFactory,
              i14.BaseLocaleComponentNgFactory,i15.AppComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(5120,i0.LOCALE_ID,i0.ɵm,[[3,i0.LOCALE_ID]]),
          i0.ɵmpd(4608,i16.NgLocalization,i16.NgLocaleLocalization,[i0.LOCALE_ID]),
          i0.ɵmpd(5120,i0.IterableDiffers,i0.ɵk,([] as any[])),i0.ɵmpd(5120,i0.KeyValueDiffers,
              i0.ɵl,([] as any[])),i0.ɵmpd(4608,i17.DomSanitizer,i17.ɵe,[i16.DOCUMENT]),
          i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i17.DomSanitizer]),i0.ɵmpd(4608,
              i17.HAMMER_GESTURE_CONFIG,i17.HammerGestureConfig,([] as any[])),i0.ɵmpd(5120,
              i17.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
                return [new i17.ɵDomEventsPlugin(p0_0),new i17.ɵKeyEventsPlugin(p1_0),
                    new i17.ɵHammerGesturesPlugin(p2_0,p2_1)];
              },[i16.DOCUMENT,i16.DOCUMENT,i16.DOCUMENT,i17.HAMMER_GESTURE_CONFIG]),
          i0.ɵmpd(4608,i17.EventManager,i17.EventManager,[i17.EVENT_MANAGER_PLUGINS,
              i0.NgZone]),i0.ɵmpd(135680,i17.ɵDomSharedStylesHost,i17.ɵDomSharedStylesHost,
              [i16.DOCUMENT]),i0.ɵmpd(4608,i17.ɵDomRendererFactory2,i17.ɵDomRendererFactory2,
              [i17.EventManager,i17.ɵDomSharedStylesHost]),i0.ɵmpd(5120,i18.AnimationDriver,
              i19.ɵc,([] as any[])),i0.ɵmpd(5120,i18.ɵAnimationStyleNormalizer,i19.ɵd,
              ([] as any[])),i0.ɵmpd(4608,i18.ɵAnimationEngine,i19.ɵb,[i18.AnimationDriver,
              i18.ɵAnimationStyleNormalizer]),i0.ɵmpd(5120,i0.RendererFactory2,i19.ɵe,
              [i17.ɵDomRendererFactory2,i18.ɵAnimationEngine,i0.NgZone]),i0.ɵmpd(6144,
              i17.ɵSharedStylesHost,(null as any),[i17.ɵDomSharedStylesHost]),i0.ɵmpd(4608,
              i0.Testability,i0.Testability,[i0.NgZone]),i0.ɵmpd(4608,i17.Meta,i17.Meta,
              [i16.DOCUMENT]),i0.ɵmpd(4608,i17.Title,i17.Title,[i16.DOCUMENT]),i0.ɵmpd(4608,
              i20.BrowserXhr,i20.BrowserXhr,([] as any[])),i0.ɵmpd(4608,i20.ResponseOptions,
              i20.BaseResponseOptions,([] as any[])),i0.ɵmpd(5120,i20.XSRFStrategy,
              i20.ɵb,([] as any[])),i0.ɵmpd(4608,i20.XHRBackend,i20.XHRBackend,[i20.BrowserXhr,
              i20.ResponseOptions,i20.XSRFStrategy]),i0.ɵmpd(4608,i20.RequestOptions,
              i20.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,i20.Http,i20.ɵc,[i20.XHRBackend,
              i20.RequestOptions]),i0.ɵmpd(4608,i21.HttpXsrfTokenExtractor,i21.ɵg,
              [i16.DOCUMENT,i0.PLATFORM_ID,i21.ɵe]),i0.ɵmpd(4608,i21.ɵh,i21.ɵh,[i21.HttpXsrfTokenExtractor,
              i21.ɵf]),i0.ɵmpd(5120,i22.PendingInterceptorService,i22.PendingInterceptorServiceFactory,
              ([] as any[])),i0.ɵmpd(5120,i21.HTTP_INTERCEPTORS,(p0_0:any,p1_0:any,
              p2_0:any) => {
            return [p0_0,new i23.AuthInterceptor(p1_0),p2_0,new i24.RefreshAuthInterceptor()];
          },[i21.ɵh,i0.Injector,i22.PendingInterceptorService]),i0.ɵmpd(4608,i21.ɵd,
              i21.ɵd,([] as any[])),i0.ɵmpd(6144,i21.XhrFactory,(null as any),[i21.ɵd]),
          i0.ɵmpd(4608,i21.HttpXhrBackend,i21.HttpXhrBackend,[i21.XhrFactory]),i0.ɵmpd(6144,
              i21.HttpBackend,(null as any),[i21.HttpXhrBackend]),i0.ɵmpd(5120,i21.HttpHandler,
              i21.ɵinterceptingHandler,[i21.HttpBackend,[2,i21.HTTP_INTERCEPTORS]]),
          i0.ɵmpd(4608,i21.HttpClient,i21.HttpClient,[i21.HttpHandler]),i0.ɵmpd(4608,
              i25.TokenStorage,i25.TokenStorage,([] as any[])),i0.ɵmpd(4608,i26.AuthenticationService,
              i26.AuthenticationService,[i21.HttpClient,i25.TokenStorage]),i0.ɵmpd(5120,
              i27.AUTH_SERVICE,i28.factory,[i26.AuthenticationService]),i0.ɵmpd(4608,
              i29.PublicGuard,i29.PublicGuard,[i27.AUTH_SERVICE,i27.PROTECTED_FALLBACK_PAGE_URI,
                  i30.Router]),i0.ɵmpd(4608,i31.ProtectedGuard,i31.ProtectedGuard,
              [i27.AUTH_SERVICE,i27.PUBLIC_FALLBACK_PAGE_URI,i30.Router]),i0.ɵmpd(4608,
              i23.AuthInterceptor,i23.AuthInterceptor,[i0.Injector]),i0.ɵmpd(5120,
              i30.ActivatedRoute,i30.ɵf,[i30.Router]),i0.ɵmpd(4608,i30.NoPreloading,
              i30.NoPreloading,([] as any[])),i0.ɵmpd(6144,i30.PreloadingStrategy,
              (null as any),[i30.NoPreloading]),i0.ɵmpd(135680,i30.RouterPreloader,
              i30.RouterPreloader,[i30.Router,i0.NgModuleFactoryLoader,i0.Compiler,
                  i0.Injector,i30.PreloadingStrategy]),i0.ɵmpd(4608,i30.PreloadAllModules,
              i30.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i30.ROUTER_INITIALIZER,
              i30.ɵi,[i30.ɵg]),i0.ɵmpd(5120,i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i30.ROUTER_INITIALIZER]),i0.ɵmpd(4608,i32.AnimationBuilder,i19.ɵBrowserAnimationBuilder,
              [i0.RendererFactory2,i17.DOCUMENT]),i0.ɵmpd(5120,i33.BREAKPOINTS,i33.DEFAULT_BREAKPOINTS_PROVIDER_FACTORY,
              ([] as any[])),i0.ɵmpd(4608,i33.BreakPointRegistry,i33.BreakPointRegistry,
              [i33.BREAKPOINTS]),i0.ɵmpd(4608,i33.MatchMedia,i33.MatchMedia,[i0.NgZone,
              i17.DOCUMENT]),i0.ɵmpd(5120,i33.MediaMonitor,i33.MEDIA_MONITOR_PROVIDER_FACTORY,
              [[3,i33.MediaMonitor],i33.BreakPointRegistry,i33.MatchMedia]),i0.ɵmpd(5120,
              i33.ObservableMedia,i33.OBSERVABLE_MEDIA_PROVIDER_FACTORY,[[3,i33.ObservableMedia],
                  i33.MatchMedia,i33.BreakPointRegistry]),i0.ɵmpd(4608,i34.FormBuilder,
              i34.FormBuilder,([] as any[])),i0.ɵmpd(4608,i34.ɵi,i34.ɵi,([] as any[])),
          i0.ɵmpd(6144,i35.DIR_DOCUMENT,(null as any),[i17.DOCUMENT]),i0.ɵmpd(4608,
              i35.Directionality,i35.Directionality,[[2,i35.DIR_DOCUMENT]]),i0.ɵmpd(4608,
              i36.Platform,i36.Platform,([] as any[])),i0.ɵmpd(4608,i37.MatMutationObserverFactory,
              i37.MatMutationObserverFactory,([] as any[])),i0.ɵmpd(5120,i38.ScrollDispatcher,
              i38.SCROLL_DISPATCHER_PROVIDER_FACTORY,[[3,i38.ScrollDispatcher],i0.NgZone,
                  i36.Platform]),i0.ɵmpd(5120,i38.ViewportRuler,i38.VIEWPORT_RULER_PROVIDER_FACTORY,
              [[3,i38.ViewportRuler],i36.Platform,i0.NgZone,i38.ScrollDispatcher]),
          i0.ɵmpd(4608,i39.InteractivityChecker,i39.InteractivityChecker,[i36.Platform]),
          i0.ɵmpd(4608,i39.FocusTrapFactory,i39.FocusTrapFactory,[i39.InteractivityChecker,
              i36.Platform,i0.NgZone]),i0.ɵmpd(136192,i39.AriaDescriber,i39.ARIA_DESCRIBER_PROVIDER_FACTORY,
              [[3,i39.AriaDescriber],i36.Platform]),i0.ɵmpd(5120,i39.LiveAnnouncer,
              i39.LIVE_ANNOUNCER_PROVIDER_FACTORY,[[3,i39.LiveAnnouncer],[2,i39.LIVE_ANNOUNCER_ELEMENT_TOKEN],
                  i36.Platform]),i0.ɵmpd(5120,i39.FocusMonitor,i39.FOCUS_MONITOR_PROVIDER_FACTORY,
              [[3,i39.FocusMonitor],i0.NgZone,i36.Platform]),i0.ɵmpd(4608,i40.ErrorStateMatcher,
              i40.ErrorStateMatcher,([] as any[])),i0.ɵmpd(5120,i41.UniqueSelectionDispatcher,
              i41.ɵa,[[3,i41.UniqueSelectionDispatcher]]),i0.ɵmpd(4608,i42.ScrollStrategyOptions,
              i42.ScrollStrategyOptions,[i38.ScrollDispatcher,i38.ViewportRuler]),
          i0.ɵmpd(5120,i42.OverlayContainer,i42.ɵa,[[3,i42.OverlayContainer]]),i0.ɵmpd(4608,
              i42.ɵf,i42.ɵf,[i38.ViewportRuler]),i0.ɵmpd(4608,i42.Overlay,i42.Overlay,
              [i42.ScrollStrategyOptions,i42.OverlayContainer,i0.ComponentFactoryResolver,
                  i42.ɵf,i0.ApplicationRef,i0.Injector,i0.NgZone]),i0.ɵmpd(5120,i42.ɵc,
              i42.ɵd,[i42.Overlay]),i0.ɵmpd(5120,i43.MAT_DIALOG_SCROLL_STRATEGY,i43.MAT_DIALOG_SCROLL_STRATEGY_PROVIDER_FACTORY,
              [i42.Overlay]),i0.ɵmpd(4608,i43.MatDialog,i43.MatDialog,[i42.Overlay,
              i0.Injector,[2,i16.Location],i43.MAT_DIALOG_SCROLL_STRATEGY,[3,i43.MatDialog]]),
          i0.ɵmpd(4608,i44.MatSnackBar,i44.MatSnackBar,[i42.Overlay,i39.LiveAnnouncer,
              i0.Injector,[3,i44.MatSnackBar]]),i0.ɵmpd(5120,i45.MAT_SELECT_SCROLL_STRATEGY,
              i45.MAT_SELECT_SCROLL_STRATEGY_PROVIDER_FACTORY,[i42.Overlay]),i0.ɵmpd(5120,
              i46.MAT_AUTOCOMPLETE_SCROLL_STRATEGY,i46.MAT_AUTOCOMPLETE_SCROLL_STRATEGY_PROVIDER_FACTORY,
              [i42.Overlay]),i0.ɵmpd(4608,i47.TranslateLoader,i48.CustomTranslateLoader,
              [i21.HttpClient]),i0.ɵmpd(4608,i49.TranslateCompiler,i49.TranslateFakeCompiler,
              ([] as any[])),i0.ɵmpd(4608,i50.TranslateParser,i50.TranslateDefaultParser,
              ([] as any[])),i0.ɵmpd(4608,i51.MissingTranslationHandler,i51.FakeMissingTranslationHandler,
              ([] as any[])),i0.ɵmpd(4608,i52.TranslateStore,i52.TranslateStore,([] as any[])),
          i0.ɵmpd(4608,i53.TranslateService,i53.TranslateService,[i52.TranslateStore,
              i47.TranslateLoader,i49.TranslateCompiler,i50.TranslateParser,i51.MissingTranslationHandler,
              i53.USE_DEFAULT_LANG,i53.USE_STORE]),i0.ɵmpd(4608,i54.ImageService,i54.ImageService,
              [i20.Http]),i0.ɵmpd(135680,i55.State,i55.State,[i55.ActionsSubject,i55.ReducerObservable,
              i55.ScannedActionsSubject,i55.INITIAL_STATE]),i0.ɵmpd(6144,i55.StateObservable,
              (null as any),[i55.State]),i0.ɵmpd(4608,i55.Store,i55.Store,[i55.StateObservable,
              i55.ActionsSubject,i55.ReducerManager]),i0.ɵmpd(4608,i56.ErrorService,
              i56.ErrorService,([] as any[])),i0.ɵmpd(4608,i57.AdminHttpRequests,i57.AdminHttpRequests,
              [i21.HttpClient,i30.Router,i56.ErrorService]),i0.ɵmpd(4608,i58.NavigationService,
              i58.NavigationService,[i55.Store]),i0.ɵmpd(135680,i59.SpinnerComponent,
              i59.SpinnerComponent,[i22.PendingInterceptorService]),i0.ɵmpd(4608,i60.Globals,
              i60.Globals,([] as any[])),i0.ɵmpd(512,i16.CommonModule,i16.CommonModule,
              ([] as any[])),i0.ɵmpd(1024,i0.ErrorHandler,i17.ɵa,([] as any[])),i0.ɵmpd(1024,
              i0.NgProbeToken,() => {
                return [i30.ɵb()];
              },([] as any[])),i0.ɵmpd(512,i30.ɵg,i30.ɵg,[i0.Injector]),i0.ɵmpd(256,
              i0.APP_ID,'secrets',([] as any[])),i0.ɵmpd(2048,i17.ɵTRANSITION_ID,(null as any),
              [i0.APP_ID]),i0.ɵmpd(1024,i0.APP_INITIALIZER,(p0_0:any,p0_1:any,p1_0:any,
              p2_0:any,p2_1:any,p2_2:any) => {
            return [i17.ɵc(p0_0,p0_1),i30.ɵh(p1_0),i17.ɵf(p2_0,p2_1,p2_2)];
          },[[2,i17.NgProbeToken],[2,i0.NgProbeToken],i30.ɵg,i17.ɵTRANSITION_ID,i16.DOCUMENT,
              i0.Injector]),i0.ɵmpd(512,i0.ApplicationInitStatus,i0.ApplicationInitStatus,
              [[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,i0.ɵe,[i0.NgZone,i0.ɵConsole,
              i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,i0.ApplicationInitStatus]),
          i0.ɵmpd(2048,i0.ApplicationRef,(null as any),[i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,
              i0.ApplicationModule,[i0.ApplicationRef]),i0.ɵmpd(512,i17.BrowserModule,
              i17.BrowserModule,[[3,i17.BrowserModule]]),i0.ɵmpd(512,i20.HttpModule,
              i20.HttpModule,([] as any[])),i0.ɵmpd(512,i21.HttpClientXsrfModule,i21.HttpClientXsrfModule,
              ([] as any[])),i0.ɵmpd(512,i21.HttpClientModule,i21.HttpClientModule,
              ([] as any[])),i0.ɵmpd(512,i61.AuthModule,i61.AuthModule,([] as any[])),
          i0.ɵmpd(512,i28.AuthenticationModule,i28.AuthenticationModule,([] as any[])),
          i0.ɵmpd(512,i62.NgHttpLoaderModule,i62.NgHttpLoaderModule,([] as any[])),
          i0.ɵmpd(512,i63.TranslateModule,i63.TranslateModule,([] as any[])),i0.ɵmpd(512,
              i64.ImageUploadModule,i64.ImageUploadModule,([] as any[])),i0.ɵmpd(1024,
              i30.ɵa,i30.ɵd,[[3,i30.Router]]),i0.ɵmpd(512,i30.UrlSerializer,i30.DefaultUrlSerializer,
              ([] as any[])),i0.ɵmpd(512,i30.ChildrenOutletContexts,i30.ChildrenOutletContexts,
              ([] as any[])),i0.ɵmpd(256,i30.ROUTER_CONFIGURATION,{},([] as any[])),
          i0.ɵmpd(1024,i16.LocationStrategy,i30.ɵc,[i16.PlatformLocation,[2,i16.APP_BASE_HREF],
              i30.ROUTER_CONFIGURATION]),i0.ɵmpd(512,i16.Location,i16.Location,[i16.LocationStrategy]),
          i0.ɵmpd(512,i0.Compiler,i0.Compiler,([] as any[])),i0.ɵmpd(512,i0.NgModuleFactoryLoader,
              i0.SystemJsNgModuleLoader,[i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),
          i0.ɵmpd(1024,i30.ROUTES,() => {
            return [[{path:'',pathMatch:'full',component:i65.HomeComponent},{path:'showroom/:name',
                component:i66.ShowroomComponent},{path:'brand/:name',component:i67.CabinetComponent},
                {path:'events/:name',component:i68.EventsComponent},{path:'admin',
                    canActivateChild:[i31.ProtectedGuard],component:i69.AdminComponent,
                    children:[{path:'cabinet',component:i70.CabinetFormComponent},
                        {path:'showroom',component:i71.ShowroomFormComponent},{path:'events',
                            component:i72.EventsFormComponent}]},{path:'not-found',
                    component:i73.PageNotFoundComponent,data:{message:'Page not found'}},
                {path:'**',redirectTo:'not-found'}]];
          },([] as any[])),i0.ɵmpd(1024,i30.Router,i30.ɵe,[i0.ApplicationRef,i30.UrlSerializer,
              i30.ChildrenOutletContexts,i16.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i30.ROUTES,i30.ROUTER_CONFIGURATION,[2,i30.UrlHandlingStrategy],
              [2,i30.RouteReuseStrategy]]),i0.ɵmpd(512,i30.RouterModule,i30.RouterModule,
              [[2,i30.ɵa],[2,i30.Router]]),i0.ɵmpd(512,i74.AppRoutingModule,i74.AppRoutingModule,
              ([] as any[])),i0.ɵmpd(131584,i55.ActionsSubject,i55.ActionsSubject,
              ([] as any[])),i0.ɵmpd(2048,i55.ReducerManagerDispatcher,(null as any),
              [i55.ActionsSubject]),i0.ɵmpd(256,i55._INITIAL_STATE,(undefined as any),
              ([] as any[])),i0.ɵmpd(1024,i55.INITIAL_STATE,i55._initialStateFactory,
              [i55._INITIAL_STATE]),i0.ɵmpd(256,i55._INITIAL_REDUCERS,{language:i75.reducer,
              menu:i76.reducer,reset:i77.reducer},([] as any[])),i0.ɵmpd(2048,i55._STORE_REDUCERS,
              (null as any),[i55._INITIAL_REDUCERS]),i0.ɵmpd(1024,i55.INITIAL_REDUCERS,
              i55._createStoreReducers,[i0.Injector,i55._INITIAL_REDUCERS,i55._STORE_REDUCERS]),
          i0.ɵmpd(256,i55._REDUCER_FACTORY,i55.combineReducers,([] as any[])),i0.ɵmpd(256,
              i55.META_REDUCERS,([] as any[]),([] as any[])),i0.ɵmpd(1024,i55.REDUCER_FACTORY,
              i55.createReducerFactory,[i55._REDUCER_FACTORY,i55.META_REDUCERS]),i0.ɵmpd(131584,
              i55.ReducerManager,i55.ReducerManager,[i55.ReducerManagerDispatcher,
                  i55.INITIAL_STATE,i55.INITIAL_REDUCERS,i55.REDUCER_FACTORY]),i0.ɵmpd(2048,
              i55.ReducerObservable,(null as any),[i55.ReducerManager]),i0.ɵmpd(131584,
              i55.ScannedActionsSubject,i55.ScannedActionsSubject,([] as any[])),i0.ɵmpd(512,
              i55.StoreRootModule,i55.StoreRootModule,[i55.ActionsSubject,i55.ReducerObservable,
                  i55.ScannedActionsSubject]),i0.ɵmpd(512,i19.BrowserAnimationsModule,
              i19.BrowserAnimationsModule,([] as any[])),i0.ɵmpd(512,i33.MediaQueriesModule,
              i33.MediaQueriesModule,([] as any[])),i0.ɵmpd(512,i33.FlexLayoutModule,
              i33.FlexLayoutModule,([] as any[])),i0.ɵmpd(512,i34.ɵba,i34.ɵba,([] as any[])),
          i0.ɵmpd(512,i34.ReactiveFormsModule,i34.ReactiveFormsModule,([] as any[])),
          i0.ɵmpd(512,i34.FormsModule,i34.FormsModule,([] as any[])),i0.ɵmpd(512,i40.CompatibilityModule,
              i40.CompatibilityModule,([] as any[])),i0.ɵmpd(512,i35.BidiModule,i35.BidiModule,
              ([] as any[])),i0.ɵmpd(256,i40.MATERIAL_SANITY_CHECKS,true,([] as any[])),
          i0.ɵmpd(512,i40.MatCommonModule,i40.MatCommonModule,[[2,i40.MATERIAL_SANITY_CHECKS]]),
          i0.ɵmpd(512,i78.PortalModule,i78.PortalModule,([] as any[])),i0.ɵmpd(512,
              i36.PlatformModule,i36.PlatformModule,([] as any[])),i0.ɵmpd(512,i40.MatRippleModule,
              i40.MatRippleModule,([] as any[])),i0.ɵmpd(512,i37.ObserversModule,i37.ObserversModule,
              ([] as any[])),i0.ɵmpd(512,i38.ScrollDispatchModule,i38.ScrollDispatchModule,
              ([] as any[])),i0.ɵmpd(512,i79.MatTabsModule,i79.MatTabsModule,([] as any[])),
          i0.ɵmpd(512,i39.A11yModule,i39.A11yModule,([] as any[])),i0.ɵmpd(512,i80.MatButtonModule,
              i80.MatButtonModule,([] as any[])),i0.ɵmpd(512,i81.MatFormFieldModule,
              i81.MatFormFieldModule,([] as any[])),i0.ɵmpd(512,i82.MatInputModule,
              i82.MatInputModule,([] as any[])),i0.ɵmpd(512,i83.MatRadioModule,i83.MatRadioModule,
              ([] as any[])),i0.ɵmpd(512,i42.OverlayModule,i42.OverlayModule,([] as any[])),
          i0.ɵmpd(512,i43.MatDialogModule,i43.MatDialogModule,([] as any[])),i0.ɵmpd(512,
              i44.MatSnackBarModule,i44.MatSnackBarModule,([] as any[])),i0.ɵmpd(512,
              i40.MatPseudoCheckboxModule,i40.MatPseudoCheckboxModule,([] as any[])),
          i0.ɵmpd(512,i40.MatOptionModule,i40.MatOptionModule,([] as any[])),i0.ɵmpd(512,
              i45.MatSelectModule,i45.MatSelectModule,([] as any[])),i0.ɵmpd(512,i84.MatCardModule,
              i84.MatCardModule,([] as any[])),i0.ɵmpd(512,i46.MatAutocompleteModule,
              i46.MatAutocompleteModule,([] as any[])),i0.ɵmpd(512,i1.AppModule,i1.AppModule,
              ([] as any[])),i0.ɵmpd(256,i21.ɵe,'XSRF-TOKEN',([] as any[])),i0.ɵmpd(256,
              i21.ɵf,'X-XSRF-TOKEN',([] as any[])),i0.ɵmpd(256,i27.PROTECTED_FALLBACK_PAGE_URI,
              '/admin',([] as any[])),i0.ɵmpd(256,i27.PUBLIC_FALLBACK_PAGE_URI,'/admin',
              ([] as any[])),i0.ɵmpd(256,i53.USE_STORE,(undefined as any),([] as any[])),
          i0.ɵmpd(256,i53.USE_DEFAULT_LANG,(undefined as any),([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovUHJvZ3JhbW1pbmcvc2VjcmV0cy9jbGllbnQvc3JjL2FwcC9hcHAubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Y6L1Byb2dyYW1taW5nL3NlY3JldHMvY2xpZW50L3NyYy9hcHAvYXBwLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
