/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './events-form.component.scss.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './events-form.component';
import * as i3 from '@ngrx/store';
import * as i4 from '../../data-services/admin-interaction-data';
const styles_EventsFormComponent:any[] = [i0.styles];
export const RenderType_EventsFormComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_EventsFormComponent,data:{}});
export function View_EventsFormComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted(-1,(null as any),['\n  events-form works!\n'])),(_l()(),i1.ɵted(-1,(null as any),
      ['\n']))],(null as any),(null as any));
}
export function View_EventsFormComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-events-form',
      ([] as any[]),(null as any),(null as any),(null as any),View_EventsFormComponent_0,
      RenderType_EventsFormComponent)),i1.ɵdid(1,245760,(null as any),0,i2.EventsFormComponent,
      [i3.Store,i4.AdminInteractionData],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const EventsFormComponentNgFactory:i1.ComponentFactory<i2.EventsFormComponent> = i1.ɵccf('app-events-form',
    i2.EventsFormComponent,View_EventsFormComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovUHJvZ3JhbW1pbmcvc2VjcmV0cy9jbGllbnQvc3JjL2FwcC9hZG1pbi9hZG1pbi1jb250ZW50L2V2ZW50cy1mb3JtL2V2ZW50cy1mb3JtLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9GOi9Qcm9ncmFtbWluZy9zZWNyZXRzL2NsaWVudC9zcmMvYXBwL2FkbWluL2FkbWluLWNvbnRlbnQvZXZlbnRzLWZvcm0vZXZlbnRzLWZvcm0uY29tcG9uZW50LnRzIiwibmc6Ly8vRjovUHJvZ3JhbW1pbmcvc2VjcmV0cy9jbGllbnQvc3JjL2FwcC9hZG1pbi9hZG1pbi1jb250ZW50L2V2ZW50cy1mb3JtL2V2ZW50cy1mb3JtLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRjovUHJvZ3JhbW1pbmcvc2VjcmV0cy9jbGllbnQvc3JjL2FwcC9hZG1pbi9hZG1pbi1jb250ZW50L2V2ZW50cy1mb3JtL2V2ZW50cy1mb3JtLmNvbXBvbmVudC50cy5FdmVudHNGb3JtQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPHA+XG4gIGV2ZW50cy1mb3JtIHdvcmtzIVxuPC9wPlxuIiwiPGFwcC1ldmVudHMtZm9ybT48L2FwcC1ldmVudHMtZm9ybT4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBLHdFQUFHO2FBQUEsaURBRUM7TUFBQTs7O29CQ0ZKO01BQUE7b0NBQUEsVUFBQTtNQUFBO0lBQUE7Ozs7In0=
