/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './page-not-found.component.scss.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './page-not-found.component';
const styles_PageNotFoundComponent:any[] = [i0.styles];
export const RenderType_PageNotFoundComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_PageNotFoundComponent,data:{}});
export function View_PageNotFoundComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'h3',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted(-1,(null as any),['This page is not found!']))],(null as any),(null as any));
}
export function View_PageNotFoundComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-page-not-found',
      ([] as any[]),(null as any),(null as any),(null as any),View_PageNotFoundComponent_0,
      RenderType_PageNotFoundComponent)),i1.ɵdid(1,114688,(null as any),0,i2.PageNotFoundComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const PageNotFoundComponentNgFactory:i1.ComponentFactory<i2.PageNotFoundComponent> = i1.ɵccf('app-page-not-found',
    i2.PageNotFoundComponent,View_PageNotFoundComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovUHJvZ3JhbW1pbmcvc2VjcmV0cy9jbGllbnQvc3JjL2FwcC9wYWdlLW5vdC1mb3VuZC9wYWdlLW5vdC1mb3VuZC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRjovUHJvZ3JhbW1pbmcvc2VjcmV0cy9jbGllbnQvc3JjL2FwcC9wYWdlLW5vdC1mb3VuZC9wYWdlLW5vdC1mb3VuZC5jb21wb25lbnQudHMiLCJuZzovLy9GOi9Qcm9ncmFtbWluZy9zZWNyZXRzL2NsaWVudC9zcmMvYXBwL3BhZ2Utbm90LWZvdW5kL3BhZ2Utbm90LWZvdW5kLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRjovUHJvZ3JhbW1pbmcvc2VjcmV0cy9jbGllbnQvc3JjL2FwcC9wYWdlLW5vdC1mb3VuZC9wYWdlLW5vdC1mb3VuZC5jb21wb25lbnQudHMuUGFnZU5vdEZvdW5kQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGgzPlRoaXMgcGFnZSBpcyBub3QgZm91bmQhPC9oMz4iLCI8YXBwLXBhZ2Utbm90LWZvdW5kPjwvYXBwLXBhZ2Utbm90LWZvdW5kPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBLHdFQUFJO2FBQUE7OztvQkNBSjtNQUFBO3NDQUFBLFVBQUE7TUFBQTtJQUFBOzs7OyJ9
