/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './events.component.scss.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './events.component';
const styles_EventsComponent:any[] = [i0.styles];
export const RenderType_EventsComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_EventsComponent,data:{}});
export function View_EventsComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'p',[['style',
      'margin-top: 200px;']],(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i1.ɵted(-1,(null as any),['\n  events works!\n'])),(_l()(),
      i1.ɵted(-1,(null as any),['\n']))],(null as any),(null as any));
}
export function View_EventsComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-events',
      ([] as any[]),(null as any),(null as any),(null as any),View_EventsComponent_0,
      RenderType_EventsComponent)),i1.ɵdid(1,114688,(null as any),0,i2.EventsComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const EventsComponentNgFactory:i1.ComponentFactory<i2.EventsComponent> = i1.ɵccf('app-events',
    i2.EventsComponent,View_EventsComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvdm92YS9Qcm9qZWN0cy9zZWNyZXRzL2NsaWVudC9zcmMvYXBwL2JyYW5kL2V2ZW50cy9ldmVudHMuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvdm92YS9Qcm9qZWN0cy9zZWNyZXRzL2NsaWVudC9zcmMvYXBwL2JyYW5kL2V2ZW50cy9ldmVudHMuY29tcG9uZW50LnRzIiwibmc6Ly8vaG9tZS92b3ZhL1Byb2plY3RzL3NlY3JldHMvY2xpZW50L3NyYy9hcHAvYnJhbmQvZXZlbnRzL2V2ZW50cy5jb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvdm92YS9Qcm9qZWN0cy9zZWNyZXRzL2NsaWVudC9zcmMvYXBwL2JyYW5kL2V2ZW50cy9ldmVudHMuY29tcG9uZW50LnRzLkV2ZW50c0NvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxwIHN0eWxlPVwibWFyZ2luLXRvcDogMjAwcHg7XCI+XG4gIGV2ZW50cyB3b3JrcyFcbjwvcD5cbiIsIjxhcHAtZXZlbnRzPjwvYXBwLWV2ZW50cz4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTtNQUFBLGdCQUE4QiwyREFFMUI7YUFBQTs7O29CQ0ZKO01BQUE7Z0NBQUEsVUFBQTtNQUFBO0lBQUE7Ozs7In0=
