/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './events-form.component.scss.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './events-form.component';
import * as i3 from '@ngrx/store';
import * as i4 from '../../data-services/admin-interaction-data';
const styles_EventsFormComponent:any[] = [i0.styles];
export const RenderType_EventsFormComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_EventsFormComponent,data:{}});
export function View_EventsFormComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted(-1,(null as any),['\n  events-form works!\n'])),(_l()(),i1.ɵted(-1,(null as any),
      ['\n']))],(null as any),(null as any));
}
export function View_EventsFormComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-events-form',
      ([] as any[]),(null as any),(null as any),(null as any),View_EventsFormComponent_0,
      RenderType_EventsFormComponent)),i1.ɵdid(1,245760,(null as any),0,i2.EventsFormComponent,
      [i3.Store,i4.AdminInteractionData],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const EventsFormComponentNgFactory:i1.ComponentFactory<i2.EventsFormComponent> = i1.ɵccf('app-events-form',
    i2.EventsFormComponent,View_EventsFormComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvdm92YS9Qcm9qZWN0cy9zZWNyZXRzL2NsaWVudC9zcmMvYXBwL2FkbWluL2FkbWluLWNvbnRlbnQvZXZlbnRzLWZvcm0vZXZlbnRzLWZvcm0uY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvdm92YS9Qcm9qZWN0cy9zZWNyZXRzL2NsaWVudC9zcmMvYXBwL2FkbWluL2FkbWluLWNvbnRlbnQvZXZlbnRzLWZvcm0vZXZlbnRzLWZvcm0uY29tcG9uZW50LnRzIiwibmc6Ly8vaG9tZS92b3ZhL1Byb2plY3RzL3NlY3JldHMvY2xpZW50L3NyYy9hcHAvYWRtaW4vYWRtaW4tY29udGVudC9ldmVudHMtZm9ybS9ldmVudHMtZm9ybS5jb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvdm92YS9Qcm9qZWN0cy9zZWNyZXRzL2NsaWVudC9zcmMvYXBwL2FkbWluL2FkbWluLWNvbnRlbnQvZXZlbnRzLWZvcm0vZXZlbnRzLWZvcm0uY29tcG9uZW50LnRzLkV2ZW50c0Zvcm1Db21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8cD5cbiAgZXZlbnRzLWZvcm0gd29ya3MhXG48L3A+XG4iLCI8YXBwLWV2ZW50cy1mb3JtPjwvYXBwLWV2ZW50cy1mb3JtPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUEsd0VBQUc7YUFBQSxpREFFQztNQUFBOzs7b0JDRko7TUFBQTtvQ0FBQSxVQUFBO01BQUE7SUFBQTs7OzsifQ==
