/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './menu.component.scss.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './menu.component';
import * as i3 from '@ngrx/store';
import * as i4 from '../../nav-service/nav-service';
import * as i5 from '@angular/router';
const styles_MenuComponent:any[] = [i0.styles];
export const RenderType_MenuComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_MenuComponent,data:{}});
export function View_MenuComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵted(-1,(null as any),['\n'])),(_l()(),i1.ɵeld(1,0,
      (null as any),(null as any),1,'div',([] as any[]),(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i1.ɵted(-1,(null as any),
      ['000'])),(_l()(),i1.ɵted(-1,(null as any),['\n'])),(_l()(),i1.ɵted(-1,(null as any),
      ['\n'])),(_l()(),i1.ɵted(-1,(null as any),['\n']))],(null as any),(null as any));
}
export function View_MenuComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-menu',([] as any[]),
      (null as any),(null as any),(null as any),View_MenuComponent_0,RenderType_MenuComponent)),
      i1.ɵdid(1,4440064,(null as any),0,i2.MenuComponent,[i3.Store,i4.NavigationService,
          i5.Router],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const MenuComponentNgFactory:i1.ComponentFactory<i2.MenuComponent> = i1.ɵccf('app-menu',
    i2.MenuComponent,View_MenuComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovUHJvZ3JhbW1pbmcvc2VjcmV0cy9jbGllbnQvc3JjL2FwcC9oZWFkZXIvbWVudS9tZW51LmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9GOi9Qcm9ncmFtbWluZy9zZWNyZXRzL2NsaWVudC9zcmMvYXBwL2hlYWRlci9tZW51L21lbnUuY29tcG9uZW50LnRzIiwibmc6Ly8vRjovUHJvZ3JhbW1pbmcvc2VjcmV0cy9jbGllbnQvc3JjL2FwcC9oZWFkZXIvbWVudS9tZW51LmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRjovUHJvZ3JhbW1pbmcvc2VjcmV0cy9jbGllbnQvc3JjL2FwcC9oZWFkZXIvbWVudS9tZW51LmNvbXBvbmVudC50cy5NZW51Q29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPCEtLSBNZW51IC0tPlxyXG48ZGl2PjAwMDwvZGl2PlxyXG48IS0tPGN1cHBhLXNsaWRlbWVudSBbbWVudWxpc3RdPVwibWVudUl0ZW1zQXJyYXlcIiAob3Blbik9XCJvbk1lbnVPcGVuKClcIiAoY2xvc2UpPVwib25NZW51Q2xvc2UoKVwiIChvbkl0ZW1TZWxlY3QpPVwib25JdGVtU2VsZWN0KCRldmVudClcIj48L2N1cHBhLXNsaWRlbWVudT4tLT5cclxuPCEtLSBNZW51IChlbmQpIC0tPlxyXG4iLCI8YXBwLW1lbnU+PC9hcHAtbWVudT4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQWEsMENBQ2I7TUFBQTtNQUFBLDRDQUFLO01BQUEsVUFBUywwQ0FDNEk7TUFBQSxTQUN2STs7O29CQ0huQjtNQUFBO2FBQUE7bUJBQUE7SUFBQTs7OzsifQ==
