/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './app.server.module';
import * as i2 from './app.component';
import * as i3 from './home/home.component.ngfactory';
import * as i4 from './brand/showroom/showroom.component.ngfactory';
import * as i5 from './brand/cabinet/cabinet.component.ngfactory';
import * as i6 from './brand/events/events.component.ngfactory';
import * as i7 from './admin/admin.component.ngfactory';
import * as i8 from './admin/admin-content/cabinet-form/cabinet-form.component.ngfactory';
import * as i9 from './admin/admin-content/showroom-form/showroom-form.component.ngfactory';
import * as i10 from './admin/admin-content/events-form/events-form.component.ngfactory';
import * as i11 from './page-not-found/page-not-found.component.ngfactory';
import * as i12 from '../node_modules/@angular/material/dialog/typings/index.ngfactory';
import * as i13 from '../node_modules/@angular/material/snack-bar/typings/index.ngfactory';
import * as i14 from './base-locale/base-locale.component.ngfactory';
import * as i15 from './app.component.ngfactory';
import * as i16 from '@angular/common';
import * as i17 from '@angular/platform-browser';
import * as i18 from '@angular/platform-server';
import * as i19 from '@angular/animations/browser';
import * as i20 from '@angular/platform-browser/animations';
import * as i21 from '@angular/http';
import * as i22 from '@angular/common/http';
import * as i23 from 'ng-http-loader/pending-interceptor.service';
import * as i24 from 'ngx-auth/src/auth.interceptor';
import * as i25 from './authentication/refresh-authInterceptor';
import * as i26 from './authentication/token-storage.service';
import * as i27 from './authentication/authentication.service';
import * as i28 from 'ngx-auth/src/tokens';
import * as i29 from './authentication/authentication.module';
import * as i30 from 'ngx-auth/src/public.guard';
import * as i31 from '@angular/router';
import * as i32 from 'ngx-auth/src/protected.guard';
import * as i33 from '@angular/animations';
import * as i34 from '@angular/flex-layout';
import * as i35 from '@angular/forms';
import * as i36 from '@angular/cdk/bidi';
import * as i37 from '@angular/cdk/platform';
import * as i38 from '@angular/cdk/observers';
import * as i39 from '@angular/cdk/scrolling';
import * as i40 from '@angular/cdk/a11y';
import * as i41 from '@angular/material/core';
import * as i42 from '@angular/cdk/collections';
import * as i43 from '@angular/cdk/overlay';
import * as i44 from '@angular/material/dialog';
import * as i45 from '@angular/material/snack-bar';
import * as i46 from '@angular/material/select';
import * as i47 from '@angular/material/autocomplete';
import * as i48 from '@ngx-translate/core/src/translate.loader';
import * as i49 from './translate-loader';
import * as i50 from '@ngx-translate/core/src/translate.compiler';
import * as i51 from '@ngx-translate/core/src/translate.parser';
import * as i52 from '@ngx-translate/core/src/missing-translation-handler';
import * as i53 from '@ngx-translate/core/src/translate.store';
import * as i54 from '@ngx-translate/core/src/translate.service';
import * as i55 from 'angular2-image-upload/lib/image-upload/image.service';
import * as i56 from '@ngrx/store';
import * as i57 from './errors/error.service';
import * as i58 from './admin/data-services/admin-http-requests';
import * as i59 from './nav-service/nav-service';
import * as i60 from 'ng-http-loader/spinner/spinner.component';
import * as i61 from '../globals/globals';
import * as i62 from 'ngx-auth/src/auth.module';
import * as i63 from 'ng-http-loader/ng-http-loader.module';
import * as i64 from '@ngx-translate/core/index';
import * as i65 from 'angular2-image-upload/lib/image-upload.module';
import * as i66 from './home/home.component';
import * as i67 from './brand/showroom/showroom.component';
import * as i68 from './brand/cabinet/cabinet.component';
import * as i69 from './brand/events/events.component';
import * as i70 from './admin/admin.component';
import * as i71 from './admin/admin-content/cabinet-form/cabinet-form.component';
import * as i72 from './admin/admin-content/showroom-form/showroom-form.component';
import * as i73 from './admin/admin-content/events-form/events-form.component';
import * as i74 from './page-not-found/page-not-found.component';
import * as i75 from './app-routing.module';
import * as i76 from './reducers/language/lang.reducer';
import * as i77 from './reducers/menu/menu.reducer';
import * as i78 from './reducers/reset-router/reset.reducer';
import * as i79 from '@angular/cdk/portal';
import * as i80 from '@angular/material/tabs';
import * as i81 from '@angular/material/button';
import * as i82 from '@angular/material/form-field';
import * as i83 from '@angular/material/input';
import * as i84 from '@angular/material/radio';
import * as i85 from '@angular/material/card';
import * as i86 from './app.module';
export const AppServerModuleNgFactory:i0.NgModuleFactory<i1.AppServerModule> = i0.ɵcmf(i1.AppServerModule,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.HomeComponentNgFactory,i4.ShowroomComponentNgFactory,i5.CabinetComponentNgFactory,
              i6.EventsComponentNgFactory,i7.AdminComponentNgFactory,i8.CabinetFormComponentNgFactory,
              i9.ShowroomFormComponentNgFactory,i10.EventsFormComponentNgFactory,i11.PageNotFoundComponentNgFactory,
              i12.MatDialogContainerNgFactory,i13.MatSnackBarContainerNgFactory,i13.SimpleSnackBarNgFactory,
              i14.BaseLocaleComponentNgFactory,i15.AppComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(5120,i0.LOCALE_ID,i0.ɵm,[[3,i0.LOCALE_ID]]),
          i0.ɵmpd(4608,i16.NgLocalization,i16.NgLocaleLocalization,[i0.LOCALE_ID]),
          i0.ɵmpd(5120,i0.IterableDiffers,i0.ɵk,([] as any[])),i0.ɵmpd(5120,i0.KeyValueDiffers,
              i0.ɵl,([] as any[])),i0.ɵmpd(4608,i17.DomSanitizer,i17.ɵe,[i16.DOCUMENT]),
          i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i17.DomSanitizer]),i0.ɵmpd(4608,
              i17.HAMMER_GESTURE_CONFIG,i17.HammerGestureConfig,([] as any[])),i0.ɵmpd(5120,
              i17.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
                return [new i17.ɵDomEventsPlugin(p0_0),new i17.ɵKeyEventsPlugin(p1_0),
                    new i17.ɵHammerGesturesPlugin(p2_0,p2_1)];
              },[i16.DOCUMENT,i16.DOCUMENT,i16.DOCUMENT,i17.HAMMER_GESTURE_CONFIG]),
          i0.ɵmpd(4608,i17.EventManager,i17.EventManager,[i17.EVENT_MANAGER_PLUGINS,
              i0.NgZone]),i0.ɵmpd(135680,i17.ɵDomSharedStylesHost,i17.ɵDomSharedStylesHost,
              [i16.DOCUMENT]),i0.ɵmpd(4608,i17.ɵDomRendererFactory2,i17.ɵDomRendererFactory2,
              [i17.EventManager,i17.ɵDomSharedStylesHost]),i0.ɵmpd(4608,i18.ɵb,i18.ɵb,
              [i17.DOCUMENT,[2,i17.ɵTRANSITION_ID]]),i0.ɵmpd(6144,i17.ɵSharedStylesHost,
              (null as any),[i18.ɵb]),i0.ɵmpd(4608,i18.ɵServerRendererFactory2,i18.ɵServerRendererFactory2,
              [i0.NgZone,i17.DOCUMENT,i17.ɵSharedStylesHost]),i0.ɵmpd(4608,i19.AnimationDriver,
              i19.ɵNoopAnimationDriver,([] as any[])),i0.ɵmpd(5120,i19.ɵAnimationStyleNormalizer,
              i20.ɵd,([] as any[])),i0.ɵmpd(4608,i19.ɵAnimationEngine,i20.ɵb,[i19.AnimationDriver,
              i19.ɵAnimationStyleNormalizer]),i0.ɵmpd(5120,i0.RendererFactory2,i18.ɵa,
              [i18.ɵServerRendererFactory2,i19.ɵAnimationEngine,i0.NgZone]),i0.ɵmpd(4352,
              i0.Testability,(null as any),([] as any[])),i0.ɵmpd(4608,i17.Meta,i17.Meta,
              [i16.DOCUMENT]),i0.ɵmpd(4608,i17.Title,i17.Title,[i16.DOCUMENT]),i0.ɵmpd(4608,
              i21.BrowserXhr,i18.ɵc,([] as any[])),i0.ɵmpd(4608,i21.ResponseOptions,
              i21.BaseResponseOptions,([] as any[])),i0.ɵmpd(4608,i21.XSRFStrategy,
              i18.ɵd,([] as any[])),i0.ɵmpd(4608,i21.XHRBackend,i21.XHRBackend,[i21.BrowserXhr,
              i21.ResponseOptions,i21.XSRFStrategy]),i0.ɵmpd(4608,i21.RequestOptions,
              i21.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,i21.Http,i18.ɵe,[i21.XHRBackend,
              i21.RequestOptions]),i0.ɵmpd(4608,i22.HttpXsrfTokenExtractor,i22.ɵg,
              [i16.DOCUMENT,i0.PLATFORM_ID,i22.ɵe]),i0.ɵmpd(4608,i22.ɵh,i22.ɵh,[i22.HttpXsrfTokenExtractor,
              i22.ɵf]),i0.ɵmpd(5120,i23.PendingInterceptorService,i23.PendingInterceptorServiceFactory,
              ([] as any[])),i0.ɵmpd(5120,i22.HTTP_INTERCEPTORS,(p0_0:any,p1_0:any,
              p2_0:any) => {
            return [p0_0,new i24.AuthInterceptor(p1_0),p2_0,new i25.RefreshAuthInterceptor()];
          },[i22.ɵh,i0.Injector,i23.PendingInterceptorService]),i0.ɵmpd(4608,i22.XhrFactory,
              i18.ɵc,([] as any[])),i0.ɵmpd(4608,i22.HttpXhrBackend,i22.HttpXhrBackend,
              [i22.XhrFactory]),i0.ɵmpd(6144,i22.HttpBackend,(null as any),[i22.HttpXhrBackend]),
          i0.ɵmpd(5120,i22.HttpHandler,i18.ɵf,[i22.HttpBackend,[2,i22.HTTP_INTERCEPTORS]]),
          i0.ɵmpd(4608,i22.HttpClient,i22.HttpClient,[i22.HttpHandler]),i0.ɵmpd(4608,
              i22.ɵd,i22.ɵd,([] as any[])),i0.ɵmpd(4608,i26.TokenStorage,i26.TokenStorage,
              ([] as any[])),i0.ɵmpd(4608,i27.AuthenticationService,i27.AuthenticationService,
              [i22.HttpClient,i26.TokenStorage]),i0.ɵmpd(5120,i28.AUTH_SERVICE,i29.factory,
              [i27.AuthenticationService]),i0.ɵmpd(4608,i30.PublicGuard,i30.PublicGuard,
              [i28.AUTH_SERVICE,i28.PROTECTED_FALLBACK_PAGE_URI,i31.Router]),i0.ɵmpd(4608,
              i32.ProtectedGuard,i32.ProtectedGuard,[i28.AUTH_SERVICE,i28.PUBLIC_FALLBACK_PAGE_URI,
                  i31.Router]),i0.ɵmpd(4608,i24.AuthInterceptor,i24.AuthInterceptor,
              [i0.Injector]),i0.ɵmpd(5120,i31.ActivatedRoute,i31.ɵf,[i31.Router]),
          i0.ɵmpd(4608,i31.NoPreloading,i31.NoPreloading,([] as any[])),i0.ɵmpd(6144,
              i31.PreloadingStrategy,(null as any),[i31.NoPreloading]),i0.ɵmpd(135680,
              i31.RouterPreloader,i31.RouterPreloader,[i31.Router,i0.NgModuleFactoryLoader,
                  i0.Compiler,i0.Injector,i31.PreloadingStrategy]),i0.ɵmpd(4608,i31.PreloadAllModules,
              i31.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i31.ROUTER_INITIALIZER,
              i31.ɵi,[i31.ɵg]),i0.ɵmpd(5120,i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i31.ROUTER_INITIALIZER]),i0.ɵmpd(4608,i33.AnimationBuilder,i20.ɵBrowserAnimationBuilder,
              [i0.RendererFactory2,i17.DOCUMENT]),i0.ɵmpd(5120,i34.BREAKPOINTS,i34.DEFAULT_BREAKPOINTS_PROVIDER_FACTORY,
              ([] as any[])),i0.ɵmpd(4608,i34.BreakPointRegistry,i34.BreakPointRegistry,
              [i34.BREAKPOINTS]),i0.ɵmpd(4608,i34.MatchMedia,i34.MatchMedia,[i0.NgZone,
              i17.DOCUMENT]),i0.ɵmpd(5120,i34.MediaMonitor,i34.MEDIA_MONITOR_PROVIDER_FACTORY,
              [[3,i34.MediaMonitor],i34.BreakPointRegistry,i34.MatchMedia]),i0.ɵmpd(5120,
              i34.ObservableMedia,i34.OBSERVABLE_MEDIA_PROVIDER_FACTORY,[[3,i34.ObservableMedia],
                  i34.MatchMedia,i34.BreakPointRegistry]),i0.ɵmpd(4608,i35.FormBuilder,
              i35.FormBuilder,([] as any[])),i0.ɵmpd(4608,i35.ɵi,i35.ɵi,([] as any[])),
          i0.ɵmpd(6144,i36.DIR_DOCUMENT,(null as any),[i17.DOCUMENT]),i0.ɵmpd(4608,
              i36.Directionality,i36.Directionality,[[2,i36.DIR_DOCUMENT]]),i0.ɵmpd(4608,
              i37.Platform,i37.Platform,([] as any[])),i0.ɵmpd(4608,i38.MatMutationObserverFactory,
              i38.MatMutationObserverFactory,([] as any[])),i0.ɵmpd(5120,i39.ScrollDispatcher,
              i39.SCROLL_DISPATCHER_PROVIDER_FACTORY,[[3,i39.ScrollDispatcher],i0.NgZone,
                  i37.Platform]),i0.ɵmpd(5120,i39.ViewportRuler,i39.VIEWPORT_RULER_PROVIDER_FACTORY,
              [[3,i39.ViewportRuler],i37.Platform,i0.NgZone,i39.ScrollDispatcher]),
          i0.ɵmpd(4608,i40.InteractivityChecker,i40.InteractivityChecker,[i37.Platform]),
          i0.ɵmpd(4608,i40.FocusTrapFactory,i40.FocusTrapFactory,[i40.InteractivityChecker,
              i37.Platform,i0.NgZone]),i0.ɵmpd(136192,i40.AriaDescriber,i40.ARIA_DESCRIBER_PROVIDER_FACTORY,
              [[3,i40.AriaDescriber],i37.Platform]),i0.ɵmpd(5120,i40.LiveAnnouncer,
              i40.LIVE_ANNOUNCER_PROVIDER_FACTORY,[[3,i40.LiveAnnouncer],[2,i40.LIVE_ANNOUNCER_ELEMENT_TOKEN],
                  i37.Platform]),i0.ɵmpd(5120,i40.FocusMonitor,i40.FOCUS_MONITOR_PROVIDER_FACTORY,
              [[3,i40.FocusMonitor],i0.NgZone,i37.Platform]),i0.ɵmpd(4608,i41.ErrorStateMatcher,
              i41.ErrorStateMatcher,([] as any[])),i0.ɵmpd(5120,i42.UniqueSelectionDispatcher,
              i42.ɵa,[[3,i42.UniqueSelectionDispatcher]]),i0.ɵmpd(4608,i43.ScrollStrategyOptions,
              i43.ScrollStrategyOptions,[i39.ScrollDispatcher,i39.ViewportRuler]),
          i0.ɵmpd(5120,i43.OverlayContainer,i43.ɵa,[[3,i43.OverlayContainer]]),i0.ɵmpd(4608,
              i43.ɵf,i43.ɵf,[i39.ViewportRuler]),i0.ɵmpd(4608,i43.Overlay,i43.Overlay,
              [i43.ScrollStrategyOptions,i43.OverlayContainer,i0.ComponentFactoryResolver,
                  i43.ɵf,i0.ApplicationRef,i0.Injector,i0.NgZone]),i0.ɵmpd(5120,i43.ɵc,
              i43.ɵd,[i43.Overlay]),i0.ɵmpd(5120,i44.MAT_DIALOG_SCROLL_STRATEGY,i44.MAT_DIALOG_SCROLL_STRATEGY_PROVIDER_FACTORY,
              [i43.Overlay]),i0.ɵmpd(4608,i44.MatDialog,i44.MatDialog,[i43.Overlay,
              i0.Injector,[2,i16.Location],i44.MAT_DIALOG_SCROLL_STRATEGY,[3,i44.MatDialog]]),
          i0.ɵmpd(4608,i45.MatSnackBar,i45.MatSnackBar,[i43.Overlay,i40.LiveAnnouncer,
              i0.Injector,[3,i45.MatSnackBar]]),i0.ɵmpd(5120,i46.MAT_SELECT_SCROLL_STRATEGY,
              i46.MAT_SELECT_SCROLL_STRATEGY_PROVIDER_FACTORY,[i43.Overlay]),i0.ɵmpd(5120,
              i47.MAT_AUTOCOMPLETE_SCROLL_STRATEGY,i47.MAT_AUTOCOMPLETE_SCROLL_STRATEGY_PROVIDER_FACTORY,
              [i43.Overlay]),i0.ɵmpd(4608,i48.TranslateLoader,i49.CustomTranslateLoader,
              [i22.HttpClient]),i0.ɵmpd(4608,i50.TranslateCompiler,i50.TranslateFakeCompiler,
              ([] as any[])),i0.ɵmpd(4608,i51.TranslateParser,i51.TranslateDefaultParser,
              ([] as any[])),i0.ɵmpd(4608,i52.MissingTranslationHandler,i52.FakeMissingTranslationHandler,
              ([] as any[])),i0.ɵmpd(4608,i53.TranslateStore,i53.TranslateStore,([] as any[])),
          i0.ɵmpd(4608,i54.TranslateService,i54.TranslateService,[i53.TranslateStore,
              i48.TranslateLoader,i50.TranslateCompiler,i51.TranslateParser,i52.MissingTranslationHandler,
              i54.USE_DEFAULT_LANG,i54.USE_STORE]),i0.ɵmpd(4608,i55.ImageService,i55.ImageService,
              [i21.Http]),i0.ɵmpd(135680,i56.State,i56.State,[i56.ActionsSubject,i56.ReducerObservable,
              i56.ScannedActionsSubject,i56.INITIAL_STATE]),i0.ɵmpd(6144,i56.StateObservable,
              (null as any),[i56.State]),i0.ɵmpd(4608,i56.Store,i56.Store,[i56.StateObservable,
              i56.ActionsSubject,i56.ReducerManager]),i0.ɵmpd(4608,i57.ErrorService,
              i57.ErrorService,([] as any[])),i0.ɵmpd(4608,i58.AdminHttpRequests,i58.AdminHttpRequests,
              [i22.HttpClient,i31.Router,i57.ErrorService]),i0.ɵmpd(4608,i59.NavigationService,
              i59.NavigationService,[i56.Store]),i0.ɵmpd(135680,i60.SpinnerComponent,
              i60.SpinnerComponent,[i23.PendingInterceptorService]),i0.ɵmpd(4608,i61.Globals,
              i61.Globals,([] as any[])),i0.ɵmpd(512,i16.CommonModule,i16.CommonModule,
              ([] as any[])),i0.ɵmpd(1024,i0.ErrorHandler,i17.ɵa,([] as any[])),i0.ɵmpd(1024,
              i0.NgProbeToken,() => {
                return [i31.ɵb()];
              },([] as any[])),i0.ɵmpd(512,i31.ɵg,i31.ɵg,[i0.Injector]),i0.ɵmpd(256,
              i0.APP_ID,'secrets',([] as any[])),i0.ɵmpd(2048,i17.ɵTRANSITION_ID,(null as any),
              [i0.APP_ID]),i0.ɵmpd(1024,i0.APP_INITIALIZER,(p0_0:any,p0_1:any,p1_0:any,
              p2_0:any,p2_1:any,p2_2:any) => {
            return [i17.ɵc(p0_0,p0_1),i31.ɵh(p1_0),i17.ɵf(p2_0,p2_1,p2_2)];
          },[[2,i17.NgProbeToken],[2,i0.NgProbeToken],i31.ɵg,i17.ɵTRANSITION_ID,i16.DOCUMENT,
              i0.Injector]),i0.ɵmpd(512,i0.ApplicationInitStatus,i0.ApplicationInitStatus,
              [[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,i0.ɵe,[i0.NgZone,i0.ɵConsole,
              i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,i0.ApplicationInitStatus]),
          i0.ɵmpd(2048,i0.ApplicationRef,(null as any),[i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,
              i0.ApplicationModule,[i0.ApplicationRef]),i0.ɵmpd(512,i17.BrowserModule,
              i17.BrowserModule,[[3,i17.BrowserModule]]),i0.ɵmpd(512,i21.HttpModule,
              i21.HttpModule,([] as any[])),i0.ɵmpd(512,i22.HttpClientXsrfModule,i22.HttpClientXsrfModule,
              ([] as any[])),i0.ɵmpd(512,i22.HttpClientModule,i22.HttpClientModule,
              ([] as any[])),i0.ɵmpd(512,i62.AuthModule,i62.AuthModule,([] as any[])),
          i0.ɵmpd(512,i29.AuthenticationModule,i29.AuthenticationModule,([] as any[])),
          i0.ɵmpd(512,i63.NgHttpLoaderModule,i63.NgHttpLoaderModule,([] as any[])),
          i0.ɵmpd(512,i64.TranslateModule,i64.TranslateModule,([] as any[])),i0.ɵmpd(512,
              i65.ImageUploadModule,i65.ImageUploadModule,([] as any[])),i0.ɵmpd(1024,
              i31.ɵa,i31.ɵd,[[3,i31.Router]]),i0.ɵmpd(512,i31.UrlSerializer,i31.DefaultUrlSerializer,
              ([] as any[])),i0.ɵmpd(512,i31.ChildrenOutletContexts,i31.ChildrenOutletContexts,
              ([] as any[])),i0.ɵmpd(256,i31.ROUTER_CONFIGURATION,{},([] as any[])),
          i0.ɵmpd(1024,i16.LocationStrategy,i31.ɵc,[i16.PlatformLocation,[2,i16.APP_BASE_HREF],
              i31.ROUTER_CONFIGURATION]),i0.ɵmpd(512,i16.Location,i16.Location,[i16.LocationStrategy]),
          i0.ɵmpd(512,i0.Compiler,i0.Compiler,([] as any[])),i0.ɵmpd(512,i0.NgModuleFactoryLoader,
              i0.SystemJsNgModuleLoader,[i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),
          i0.ɵmpd(1024,i31.ROUTES,() => {
            return [[{path:'',pathMatch:'full',component:i66.HomeComponent},{path:'showroom/:name',
                component:i67.ShowroomComponent},{path:'brand/:name',component:i68.CabinetComponent},
                {path:'events/:name',component:i69.EventsComponent},{path:'admin',
                    canActivateChild:[i32.ProtectedGuard],component:i70.AdminComponent,
                    children:[{path:'cabinet',component:i71.CabinetFormComponent},
                        {path:'showroom',component:i72.ShowroomFormComponent},{path:'events',
                            component:i73.EventsFormComponent}]},{path:'not-found',
                    component:i74.PageNotFoundComponent,data:{message:'Page not found'}},
                {path:'**',redirectTo:'not-found'}]];
          },([] as any[])),i0.ɵmpd(1024,i31.Router,i31.ɵe,[i0.ApplicationRef,i31.UrlSerializer,
              i31.ChildrenOutletContexts,i16.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i31.ROUTES,i31.ROUTER_CONFIGURATION,[2,i31.UrlHandlingStrategy],
              [2,i31.RouteReuseStrategy]]),i0.ɵmpd(512,i31.RouterModule,i31.RouterModule,
              [[2,i31.ɵa],[2,i31.Router]]),i0.ɵmpd(512,i75.AppRoutingModule,i75.AppRoutingModule,
              ([] as any[])),i0.ɵmpd(131584,i56.ActionsSubject,i56.ActionsSubject,
              ([] as any[])),i0.ɵmpd(2048,i56.ReducerManagerDispatcher,(null as any),
              [i56.ActionsSubject]),i0.ɵmpd(256,i56._INITIAL_STATE,(undefined as any),
              ([] as any[])),i0.ɵmpd(1024,i56.INITIAL_STATE,i56._initialStateFactory,
              [i56._INITIAL_STATE]),i0.ɵmpd(256,i56._INITIAL_REDUCERS,{language:i76.reducer,
              menu:i77.reducer,reset:i78.reducer},([] as any[])),i0.ɵmpd(2048,i56._STORE_REDUCERS,
              (null as any),[i56._INITIAL_REDUCERS]),i0.ɵmpd(1024,i56.INITIAL_REDUCERS,
              i56._createStoreReducers,[i0.Injector,i56._INITIAL_REDUCERS,i56._STORE_REDUCERS]),
          i0.ɵmpd(256,i56._REDUCER_FACTORY,i56.combineReducers,([] as any[])),i0.ɵmpd(256,
              i56.META_REDUCERS,([] as any[]),([] as any[])),i0.ɵmpd(1024,i56.REDUCER_FACTORY,
              i56.createReducerFactory,[i56._REDUCER_FACTORY,i56.META_REDUCERS]),i0.ɵmpd(131584,
              i56.ReducerManager,i56.ReducerManager,[i56.ReducerManagerDispatcher,
                  i56.INITIAL_STATE,i56.INITIAL_REDUCERS,i56.REDUCER_FACTORY]),i0.ɵmpd(2048,
              i56.ReducerObservable,(null as any),[i56.ReducerManager]),i0.ɵmpd(131584,
              i56.ScannedActionsSubject,i56.ScannedActionsSubject,([] as any[])),i0.ɵmpd(512,
              i56.StoreRootModule,i56.StoreRootModule,[i56.ActionsSubject,i56.ReducerObservable,
                  i56.ScannedActionsSubject]),i0.ɵmpd(512,i20.BrowserAnimationsModule,
              i20.BrowserAnimationsModule,([] as any[])),i0.ɵmpd(512,i34.MediaQueriesModule,
              i34.MediaQueriesModule,([] as any[])),i0.ɵmpd(512,i34.FlexLayoutModule,
              i34.FlexLayoutModule,([] as any[])),i0.ɵmpd(512,i35.ɵba,i35.ɵba,([] as any[])),
          i0.ɵmpd(512,i35.ReactiveFormsModule,i35.ReactiveFormsModule,([] as any[])),
          i0.ɵmpd(512,i35.FormsModule,i35.FormsModule,([] as any[])),i0.ɵmpd(512,i41.CompatibilityModule,
              i41.CompatibilityModule,([] as any[])),i0.ɵmpd(512,i36.BidiModule,i36.BidiModule,
              ([] as any[])),i0.ɵmpd(256,i41.MATERIAL_SANITY_CHECKS,true,([] as any[])),
          i0.ɵmpd(512,i41.MatCommonModule,i41.MatCommonModule,[[2,i41.MATERIAL_SANITY_CHECKS]]),
          i0.ɵmpd(512,i79.PortalModule,i79.PortalModule,([] as any[])),i0.ɵmpd(512,
              i37.PlatformModule,i37.PlatformModule,([] as any[])),i0.ɵmpd(512,i41.MatRippleModule,
              i41.MatRippleModule,([] as any[])),i0.ɵmpd(512,i38.ObserversModule,i38.ObserversModule,
              ([] as any[])),i0.ɵmpd(512,i39.ScrollDispatchModule,i39.ScrollDispatchModule,
              ([] as any[])),i0.ɵmpd(512,i80.MatTabsModule,i80.MatTabsModule,([] as any[])),
          i0.ɵmpd(512,i40.A11yModule,i40.A11yModule,([] as any[])),i0.ɵmpd(512,i81.MatButtonModule,
              i81.MatButtonModule,([] as any[])),i0.ɵmpd(512,i82.MatFormFieldModule,
              i82.MatFormFieldModule,([] as any[])),i0.ɵmpd(512,i83.MatInputModule,
              i83.MatInputModule,([] as any[])),i0.ɵmpd(512,i84.MatRadioModule,i84.MatRadioModule,
              ([] as any[])),i0.ɵmpd(512,i43.OverlayModule,i43.OverlayModule,([] as any[])),
          i0.ɵmpd(512,i44.MatDialogModule,i44.MatDialogModule,([] as any[])),i0.ɵmpd(512,
              i45.MatSnackBarModule,i45.MatSnackBarModule,([] as any[])),i0.ɵmpd(512,
              i41.MatPseudoCheckboxModule,i41.MatPseudoCheckboxModule,([] as any[])),
          i0.ɵmpd(512,i41.MatOptionModule,i41.MatOptionModule,([] as any[])),i0.ɵmpd(512,
              i46.MatSelectModule,i46.MatSelectModule,([] as any[])),i0.ɵmpd(512,i85.MatCardModule,
              i85.MatCardModule,([] as any[])),i0.ɵmpd(512,i47.MatAutocompleteModule,
              i47.MatAutocompleteModule,([] as any[])),i0.ɵmpd(512,i86.AppModule,i86.AppModule,
              ([] as any[])),i0.ɵmpd(512,i20.NoopAnimationsModule,i20.NoopAnimationsModule,
              ([] as any[])),i0.ɵmpd(512,i18.ServerModule,i18.ServerModule,([] as any[])),
          i0.ɵmpd(512,i1.AppServerModule,i1.AppServerModule,([] as any[])),i0.ɵmpd(256,
              i22.ɵe,'XSRF-TOKEN',([] as any[])),i0.ɵmpd(256,i22.ɵf,'X-XSRF-TOKEN',
              ([] as any[])),i0.ɵmpd(256,i28.PROTECTED_FALLBACK_PAGE_URI,'/admin',
              ([] as any[])),i0.ɵmpd(256,i28.PUBLIC_FALLBACK_PAGE_URI,'/admin',([] as any[])),
          i0.ɵmpd(256,i54.USE_STORE,(undefined as any),([] as any[])),i0.ɵmpd(256,
              i54.USE_DEFAULT_LANG,(undefined as any),([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvdm92YS9Qcm9qZWN0cy9zZWNyZXRzL2NsaWVudC9zcmMvYXBwL2FwcC5zZXJ2ZXIubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvdm92YS9Qcm9qZWN0cy9zZWNyZXRzL2NsaWVudC9zcmMvYXBwL2FwcC5zZXJ2ZXIubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
