/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './authentication.module';
import * as i2 from './token-storage.service';
import * as i3 from './authentication.service';
import * as i4 from '@angular/common/http';
import * as i5 from 'ngx-auth/src/tokens';
import * as i6 from 'ngx-auth/src/public.guard';
import * as i7 from '@angular/router';
import * as i8 from 'ngx-auth/src/protected.guard';
import * as i9 from 'ngx-auth/src/auth.interceptor';
import * as i10 from 'ngx-auth/src/auth.module';
export const AuthenticationModuleNgFactory:i0.NgModuleFactory<i1.AuthenticationModule> = i0.ɵcmf(i1.AuthenticationModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.TokenStorage,i2.TokenStorage,([] as any[])),i0.ɵmpd(4608,i3.AuthenticationService,
          i3.AuthenticationService,[i4.HttpClient,i2.TokenStorage]),i0.ɵmpd(5120,i5.AUTH_SERVICE,
          i1.factory,[i3.AuthenticationService]),i0.ɵmpd(4608,i6.PublicGuard,i6.PublicGuard,
          [i5.AUTH_SERVICE,i5.PROTECTED_FALLBACK_PAGE_URI,i7.Router]),i0.ɵmpd(4608,
          i8.ProtectedGuard,i8.ProtectedGuard,[i5.AUTH_SERVICE,i5.PUBLIC_FALLBACK_PAGE_URI,
              i7.Router]),i0.ɵmpd(4608,i9.AuthInterceptor,i9.AuthInterceptor,[i0.Injector]),
          i0.ɵmpd(5120,i4.HTTP_INTERCEPTORS,(p0_0:any) => {
            return [new i9.AuthInterceptor(p0_0)];
          },[i0.Injector]),i0.ɵmpd(512,i10.AuthModule,i10.AuthModule,([] as any[])),
          i0.ɵmpd(512,i1.AuthenticationModule,i1.AuthenticationModule,([] as any[])),
          i0.ɵmpd(256,i5.PROTECTED_FALLBACK_PAGE_URI,'/admin',([] as any[])),i0.ɵmpd(256,
              i5.PUBLIC_FALLBACK_PAGE_URI,'/admin',([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovUHJvZ3JhbW1pbmcvc2VjcmV0cy9jbGllbnQvc3JjL2FwcC9hdXRoZW50aWNhdGlvbi9hdXRoZW50aWNhdGlvbi5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRjovUHJvZ3JhbW1pbmcvc2VjcmV0cy9jbGllbnQvc3JjL2FwcC9hdXRoZW50aWNhdGlvbi9hdXRoZW50aWNhdGlvbi5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
