/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './events.component.scss.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './events.component';
const styles_EventsComponent:any[] = [i0.styles];
export const RenderType_EventsComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_EventsComponent,data:{}});
export function View_EventsComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'p',[['style',
      'margin-top: 200px;']],(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i1.ɵted(-1,(null as any),['\n  events works!\n'])),(_l()(),
      i1.ɵted(-1,(null as any),['\n']))],(null as any),(null as any));
}
export function View_EventsComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-events',
      ([] as any[]),(null as any),(null as any),(null as any),View_EventsComponent_0,
      RenderType_EventsComponent)),i1.ɵdid(1,114688,(null as any),0,i2.EventsComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const EventsComponentNgFactory:i1.ComponentFactory<i2.EventsComponent> = i1.ɵccf('app-events',
    i2.EventsComponent,View_EventsComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovUHJvZ3JhbW1pbmcvc2VjcmV0cy9jbGllbnQvc3JjL2FwcC9icmFuZC9ldmVudHMvZXZlbnRzLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9GOi9Qcm9ncmFtbWluZy9zZWNyZXRzL2NsaWVudC9zcmMvYXBwL2JyYW5kL2V2ZW50cy9ldmVudHMuY29tcG9uZW50LnRzIiwibmc6Ly8vRjovUHJvZ3JhbW1pbmcvc2VjcmV0cy9jbGllbnQvc3JjL2FwcC9icmFuZC9ldmVudHMvZXZlbnRzLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRjovUHJvZ3JhbW1pbmcvc2VjcmV0cy9jbGllbnQvc3JjL2FwcC9icmFuZC9ldmVudHMvZXZlbnRzLmNvbXBvbmVudC50cy5FdmVudHNDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8cCBzdHlsZT1cIm1hcmdpbi10b3A6IDIwMHB4O1wiPlxyXG4gIGV2ZW50cyB3b3JrcyFcclxuPC9wPlxyXG4iLCI8YXBwLWV2ZW50cz48L2FwcC1ldmVudHM+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7TUFBQSxnQkFBOEIsMkRBRTFCO2FBQUE7OztvQkNGSjtNQUFBO2dDQUFBLFVBQUE7TUFBQTtJQUFBOzs7OyJ9
