/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './showroom.component.scss.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './showroom.component';
const styles_ShowroomComponent:any[] = [i0.styles];
export const RenderType_ShowroomComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_ShowroomComponent,data:{}});
export function View_ShowroomComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'p',[['style',
      'margin-top: 200px;']],(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i1.ɵted(-1,(null as any),['\n  showroom works!\n'])),
      (_l()(),i1.ɵted(-1,(null as any),['\n']))],(null as any),(null as any));
}
export function View_ShowroomComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-showroom',
      ([] as any[]),(null as any),(null as any),(null as any),View_ShowroomComponent_0,
      RenderType_ShowroomComponent)),i1.ɵdid(1,114688,(null as any),0,i2.ShowroomComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const ShowroomComponentNgFactory:i1.ComponentFactory<i2.ShowroomComponent> = i1.ɵccf('app-showroom',
    i2.ShowroomComponent,View_ShowroomComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovUHJvZ3JhbW1pbmcvc2VjcmV0cy9jbGllbnQvc3JjL2FwcC9icmFuZC9zaG93cm9vbS9zaG93cm9vbS5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRjovUHJvZ3JhbW1pbmcvc2VjcmV0cy9jbGllbnQvc3JjL2FwcC9icmFuZC9zaG93cm9vbS9zaG93cm9vbS5jb21wb25lbnQudHMiLCJuZzovLy9GOi9Qcm9ncmFtbWluZy9zZWNyZXRzL2NsaWVudC9zcmMvYXBwL2JyYW5kL3Nob3dyb29tL3Nob3dyb29tLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRjovUHJvZ3JhbW1pbmcvc2VjcmV0cy9jbGllbnQvc3JjL2FwcC9icmFuZC9zaG93cm9vbS9zaG93cm9vbS5jb21wb25lbnQudHMuU2hvd3Jvb21Db21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8cCBzdHlsZT1cIm1hcmdpbi10b3A6IDIwMHB4O1wiPlxyXG4gIHNob3dyb29tIHdvcmtzIVxyXG48L3A+XHJcbiIsIjxhcHAtc2hvd3Jvb20+PC9hcHAtc2hvd3Jvb20+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7TUFBQSxnQkFBOEI7TUFFMUI7OztvQkNGSjtNQUFBO2tDQUFBLFVBQUE7TUFBQTtJQUFBOzs7OyJ9
