/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './showroom.component.scss.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './showroom.component';
const styles_ShowroomComponent:any[] = [i0.styles];
export const RenderType_ShowroomComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_ShowroomComponent,data:{}});
export function View_ShowroomComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'p',[['style',
      'margin-top: 200px;']],(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i1.ɵted(-1,(null as any),['\n  showroom works!\n'])),
      (_l()(),i1.ɵted(-1,(null as any),['\n']))],(null as any),(null as any));
}
export function View_ShowroomComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-showroom',
      ([] as any[]),(null as any),(null as any),(null as any),View_ShowroomComponent_0,
      RenderType_ShowroomComponent)),i1.ɵdid(1,114688,(null as any),0,i2.ShowroomComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const ShowroomComponentNgFactory:i1.ComponentFactory<i2.ShowroomComponent> = i1.ɵccf('app-showroom',
    i2.ShowroomComponent,View_ShowroomComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvdm92YS9Qcm9qZWN0cy9zZWNyZXRzL2NsaWVudC9zcmMvYXBwL2JyYW5kL3Nob3dyb29tL3Nob3dyb29tLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL3ZvdmEvUHJvamVjdHMvc2VjcmV0cy9jbGllbnQvc3JjL2FwcC9icmFuZC9zaG93cm9vbS9zaG93cm9vbS5jb21wb25lbnQudHMiLCJuZzovLy9ob21lL3ZvdmEvUHJvamVjdHMvc2VjcmV0cy9jbGllbnQvc3JjL2FwcC9icmFuZC9zaG93cm9vbS9zaG93cm9vbS5jb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvdm92YS9Qcm9qZWN0cy9zZWNyZXRzL2NsaWVudC9zcmMvYXBwL2JyYW5kL3Nob3dyb29tL3Nob3dyb29tLmNvbXBvbmVudC50cy5TaG93cm9vbUNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxwIHN0eWxlPVwibWFyZ2luLXRvcDogMjAwcHg7XCI+XG4gIHNob3dyb29tIHdvcmtzIVxuPC9wPlxuIiwiPGFwcC1zaG93cm9vbT48L2FwcC1zaG93cm9vbT4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTtNQUFBLGdCQUE4QjtNQUUxQjs7O29CQ0ZKO01BQUE7a0NBQUEsVUFBQTtNQUFBO0lBQUE7Ozs7In0=
